### PR TITLE
Revert "Adds Log in for frost-api accounts"

### PR DESCRIPTION
**Pull request by lautarodragan**
@jwicks31 merging to master deploys to production. We shouldn't merge to master things that aren't ready for prime time.

This PR introduced the need for users to be logged-in (and registered, which is unavailable) to be able to see works. I'm not sure it's desirable to put such a wall since all Po.et Badges link to works.

### CODE REVIEW

**Comment by lautarodragan** [comment]
Further commenting: we don't want the `master` branch, or even `testing`, to be "breakable" or have half-features, either. 

If we want to create smaller PRs, we can create feature-branches and sub-feature-branches and create PRs from `sub-feature-branch` to `feature-branch`, and once `feature-branch` is ready for prime time, PR from `feature-branch` to `master`.

All PRs have Netlify previews which means anyone can access them and play around, so there's no need to merge anything to preview it or share it.

**Comment by lautarodragan** [comment]
Another comment: new features should also be toggled off by default until prod testing is complete

Final note: to get this feature back we'll need to revert this PR (yes, revert the revert). 

Revering actually creates a revert branch (this one is named `revert-91-accounts_#79`). We can continue working on the feature on `revert-revert-91-accounts_#79` afterwards.

**Comment by lautarodragan** [comment]
@wzalazar can you please review this one ASAP? 

@warrenv @geoffturk (not urgent) see comments above.

**Comment by lautarodragan** [comment]
For reference: the only functioning screen we have right now is the work-by-id view.

You can see the preview of that screen for this PR here: https://deploy-preview-97--poet-explorer.netlify.com/works/c481118d5ac0527fca2023d3650744c723bb742fcb5977871df4a3d74d0bc1cb

**Review by wzalazar — APPROVED** [review]

**Pull request merged**
