### PR TITLE
Configurable Frost Api Url

### LINKED ISSUE #142: Configurable Frost API URL
Right now, even though the Frost API URL is configurable, a few sagas are hard-coding `const frost = new Frost({ host: '/api' })`.

This will be problematic once we stop using Netlify redirects to communicate with the Frost API and hit it directly instead.

See for example:

https://github.com/poetapp/explorer-web/blob/5b0069b8adc8f61fe2f38df484418c130cde19b2/src/sagas/SignIn.ts#L8-L15

Originally a comment in https://github.com/poetapp/explorer-web/pull/98/.

Related to https://github.com/poetapp/explorer-web/issues/143

### PR DESCRIPTION
**Pull request by jwicks31**
Resolves #142 

### PR Review Checklist

* [ ] **Do the changes match the product spec?**
* [ ] **Are there changes in this PR that weren't originally in the product spec?**
* [ ] **Is a feature toggle introduced for this PR? Is it disabled by default?**
* [ ] **Have you tested the changes?**
* [ ] **Is QE review required? If so, has this been reviewed by QE?** (For all new features, review by QE is required. Minor changes which already have passing functional tests may not need a new QE review -- when in doubt, loop in a QE reviewer).
* [ ] **Are there code changes that require new unit tests? If so, are those tests included?** (A separate PR for tests is not appropriate).
* [ ] **Are documentation updates required? If so, does this PR include it?** (Separate documentation PR is generally not appropriate).
* [ ] **Are the added/edited files named appropriately and located correctly in the project directory structure?**

### Warning

Merging to `master` automatically triggers a deploy in production.

### CODE REVIEW

**Comment by jwicks31** [comment]
I can get this to work correctly with the following code (after changing the dev environment frostApiUrl:
```ts
export async function signInFrost(email: string, password: string): Promise<{ readonly token: string }> {
  return await FrostClient.login(email, password)
}
```
Then inside of the saga I have: 
```ts
    const { token } = yield call(signInFrost, email, password)
```
I'm not really sure why it fails whenever I try just doing:

```ts
    const { token } = yield call(FrostClient.login, email, password)
```

**Comment by wzalazar** [comment]
do you use local-dev? @jwicks31 

if you are using local-dev, you must to specify the new env var

```
environment:
      - FROST_API=http://frost-api:3000
```

**Comment by jwicks31** [comment]
I am using local-dev, but I have that environment variable in there already.

**Comment by wzalazar** [comment]
@jwicks31 

you are losing the `context` for `Frost-client`, you need to specified this `context` in this line

```
const { token } = yield call([FrostClient, FrostClient.login], email, password)
```

or 

```
const { token } = yield call(FrostClient.login.bind(FrostClient), email, password)
```

**Comment by lautarodragan** [comment]
Thanks @wzalazar! 

In my case it worked without binding:

https://github.com/poetapp/explorer-web/blob/3615760018a6deaaac565759e2835f117e328a12/src/sagas/GetProfile.ts#L16-L24

Although maybe it wasn't really working and I just didn't test it? Does the GetProfile saga get executed when I log in? 

@jwicks31

**Comment by jwicks31** [comment]
@wzalazar Thank you!

@lautarodragan Yeah it is executed whenever you login and looks like it was failing as well. I went ahead and updated it here.

**Comment by jwicks31** [comment]
Ok everything is working when running locally and updating the dev environment to 
`"frostApiUrl": "/api"`

But I am getting this error message when trying to sign in with Netilify:
`
Failed to load https://api.frost.po.et/login: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://deploy-preview-147--poet-explorer.netlify.com' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

**Comment by lautarodragan** [comment]
I don't know why that error is occurring and haven't been able to debug it yet, but was able to reproduce it.

Oddly enough, after refreshing the page, going to /login redirects me to the home and checking the redux state shows that I'm logged in — so it would seem that much did work...

**Comment by wzalazar** [comment]
@jwicks31 

the problem is because you are doing the request directly to `https://api.frost.po.et/login`.  You have to use always `/api` for `frostApiUrl `. With this value always the request url will be 

`{host-web}/api/login`

`host-web`: can be, `https://explorer.po.et/` or whatever

but when you use `/api` the redirects will resolve the request

**Review by wzalazar — APPROVED** [review]

**Review by lautarodragan — APPROVED** [review]

**Pull request merged**
