### PR TITLE
Test Saga

### PR DESCRIPTION
**Pull request by lautarodragan**
This PR reduces complexity in sagas by removing a function that was simply wrapping another function.

It also makes the Frost API URL configurable, which is a requirement for multi-environment deploys.

## Issue with Tests

Files that depend on configuration cause tests to fail, since configuration is injected into the project at build time via webpack, but unit tests are using ts-node. 

Even though the tests themselves don't depend on the configuration, when they import files that do, ts-node fails because it can't `require('Configuration')` since `'Configuration'` is not an actual file but an alias.

This is the reason Netlify is building without problems but Travis is failing.

See https://github.com/poetapp/explorer-web/issues/135

### CODE REVIEW

**Comment by wzalazar** [comment]
I tested in my local, and it works properly. 

Do you have the same issue in your local @lautarodragan?

Note: I noticed there is another problem the command `npm run lint` fails also

**Comment by lautarodragan** [comment]
@wzalazar what do you mean it worked perfectly? `npm t` passes without issues?

**Comment by wzalazar** [comment]
> @wzalazar what do you mean it worked perfectly? npm t passes without issues?

yes, in my laptop works fine

**Comment by jwicks31** [comment]
@lautarodragan looks good! I was able to run the tests in my local dev environment as well and they all passed.

**Comment by wzalazar** [comment]
I fixed the `Travis CI` adding 

```
 "paths": {
      "Configuration": [
         "../env/development.json"
       ]
     }
   },	
```

it's necessary for `ts-node` and `tsc`.  

When you use `webpack` for building it still working with dynamic files and works fine.

**Comment by lautarodragan** [comment]
@wzalazar you're awesome :sunglasses:

**Pull request merged**
