### PR TITLE
Adds Storybook to Explorer-web

### LINKED ISSUE #34: Add Storybook to explorer-web

### PR DESCRIPTION
**Pull request by jwicks31**
Added storybook and a simple button component to test storybook. 

Resolves #34

### CODE REVIEW

**Review by lautarodragan — DISMISSED** [review]
- Try using TS for .stories
- Try adding config to webpack to ignore .stories files (in the normal build)

**Comment by wzalazar** [comment]
@lautarodragan @jwicks31 it's ready to check!

**Comment by jwicks31** [comment]
LGTM!

**Review by lautarodragan — APPROVED** [review]
Awesome job :rocket:

**Pull request merged**
