### PR TITLE
QA Environment- Testnet/Mainnet 

### LINKED ISSUE #1: Extract Web from Poet
This is important to ease adoption of the code base to new developers as well as working on the existing code base.

Code
- https://github.com/poetapp/poet/tree/master/web

Makefile
- https://github.com/poetapp/poet/blob/master/makefile

Docker Files: 
- https://github.com/poetapp/poet/blob/master/Docker/web-poet-js-local.dockerfile
- https://github.com/poetapp/poet/blob/master/Docker/web-poet-js-remote.dockerfile

To preserve commit history, try to use [git filter-branch --prune-empty --subdirectory-filter web master](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/).

### LINKED ISSUE #2: Work Screen : Attributes : Author
The value for `author` can either be a plain string or the id of a profile in Poet.

When it's the ID of a profile, it should be displayed as a link to that profile, with the profile's name.

work author

### PR DESCRIPTION
**Pull request by jwicks31**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

## Description of Changes

`Fixes #1, Resolves #2`

### Warning

Merging to `master` automatically triggers a deploy in production.

### CODE REVIEW

**Comment by geoffturk** [comment]
Make `apiUrl` an env var so we can set it to test/live accordingly.

https://github.com/poetapp/explorer-web/blob/127ca04e3d260db02df55552367c893e8dc561bb/env/testing.json

**Review by WesleyCharlesBlake — COMMENTED** [review]
Should we be pointing explorer web to frost-api or node?

**Comment by geoffturk** [comment]
Node. There should really be two explorer-web instances, one pointing to each node (Live/Test). Just pointing this one instance to testnet is good enough for the moment.

**Comment by WesleyCharlesBlake** [comment]
@jwicks31 will need to update the the apiUrl to point to https://explorer-testnet.qa.poetnetwork.net/ instead of frost-api.qa

**Pull request closed without merging**
