### PR TITLE
Updates Redirects

### LINKED ISSUE #143: Per-Environment Netlify Redirects
We currently have only one Netlify Redirects file:

https://github.com/poetapp/explorer-web/blob/5b0069b8adc8f61fe2f38df484418c130cde19b2/_redirects#L1-L2

We need to have different _redirects file for different environments, so PR previews use the testing environment of Frost.

See how this is done in Frost for reference.

Issue introduced in https://github.com/poetapp/explorer-web/pull/98/.

### PR DESCRIPTION
**Pull request by jwicks31**
Fixes #143 

### Description of Changes

- Adds redirect file for testing and production environments
- Updates webpack to look for the correct redirect file

### PR Review Checklist

* [ ] **Do the changes match the product spec?**
* [ ] **Are there changes in this PR that weren't originally in the product spec?**
* [ ] **Is a feature toggle introduced for this PR? Is it disabled by default?**
* [ ] **Have you tested the changes?**
* [ ] **Is QE review required? If so, has this been reviewed by QE?** (For all new features, review by QE is required. Minor changes which already have passing functional tests may not need a new QE review -- when in doubt, loop in a QE reviewer).
* [ ] **Are there code changes that require new unit tests? If so, are those tests included?** (A separate PR for tests is not appropriate).
* [ ] **Are documentation updates required? If so, does this PR include it?** (Separate documentation PR is generally not appropriate).
* [ ] **Are the added/edited files named appropriately and located correctly in the project directory structure?**

### Warning

Merging to `master` automatically triggers a deploy in production.

### CODE REVIEW

**Review by wzalazar — DISMISSED** [review]
Excellent!

**Comment by lautarodragan** [comment]
@wzalazar can you test whether you can create an account in the testing environment Frost and log into it in the deploy preview of this branch?

Deploy previews of explorer-web should use the testing environment of the frost api

I tried doing that but I'm getting a "The specified resource does not exist"

**Comment by wzalazar** [comment]
yes, you are right @lautarodragan. The reason is that Netlify is using `npm run build` command. We need to create a `netlify.toml`

**Comment by lautarodragan** [comment]
Thanks! Can you help Jesse with that?

**Comment by wzalazar** [comment]
yes, sure! @lautarodragan

**Comment by wzalazar** [comment]
@lautarodragan can you check now? it works for me

**Review by lautarodragan — APPROVED** [review]

**Review by warrenv — APPROVED** [review]

**Pull request merged**
