### PR TITLE
new logos

### PR DESCRIPTION
**Pull request by lautarodragan**

### CODE REVIEW

**Comment by ericelliott** [comment]
Can you add before/after screenshots to PRs with visual changes?

**Comment by lautarodragan** [comment]
@ericelliott this was a change pushed by @pat-riley , I just created the PR.

Pat, you can see the deploy preview of how the logos would look like [in the home](https://deploy-preview-20--poet-explorer.netlify.com/), compared to how they [look today](https://explorer.po.et/).

Can you confirm this is how it should look?

In the work-by-id page it seems to break the upper-left logo for some reason. See [new](https://explorer.po.et/works/c481118d5ac0527fca2023d3650744c723bb742fcb5977871df4a3d74d0bc1cb) vs [now](https://deploy-preview-20--poet-explorer.netlify.com/works/c481118d5ac0527fca2023d3650744c723bb742fcb5977871df4a3d74d0bc1cb).

Looks like we were setting neither `width` nor `height` there, and for the old file the size was being inferred to 99x31px but with the new image it's 0x0. 

Setting the `width` to `100px` for the new one seems to fix it.

**Comment by lautarodragan** [comment]
Yup, that seems to have fixed it. LMK if this is ready to merge.

**Review by pat-riley — APPROVED** [review]
yes this looks good - tested on chrome and safari

**Pull request merged**
