### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by geoffturk**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

## Description of Changes

Some minor edits to the README and description in package.json

### Warning

Merging to `master` automatically triggers a deploy in production.

### CODE REVIEW

**Comment by geoffturk** [comment]
I'm not sure why the Netlify preview failed here and in the frost-web repo for a similar PR.

**Review by warrenv — APPROVED** [review]
* [n/a] Tested changes manually
* [n/a] Checked accidental architectural/style changes
* [x] Reviewed entire diff
* [n/a] Unit tests
* [x] Documentation
* [x] Filenames and locations

**Comment by warrenv** [comment]
It's been happening on nearly all the netlify builds since the node 10.x update. Click on 'Details' next to the netlify fail, click on 'Retry deply' and click the 'clear cache' checkbox. I plan on following up with them after all the lockfile issues get straightened out on our end if the problem persists.

**Comment by geoffturk** [comment]
I don't seem to have a "Retry deploy" button or "Clear cache" checkbox available to me in Netlify...

image

**Comment by geoffturk** [comment]
@wzalazar sorted me out with Netlify so I am redeploying the preview there.

**Review by wzalazar — APPROVED** [review]
* [n/a] Tested changes manually
* [n/a] Checked accidental architectural/style changes
* [x] Reviewed entire diff
* [n/a] Unit tests
* [x] Documentation
* [x] Filenames and locations

**Pull request merged**
