### PR TITLE
chore: Env vars Netlify

### LINKED ISSUE #1: Extract Web from Poet
This is important to ease adoption of the code base to new developers as well as working on the existing code base.

Code
- https://github.com/poetapp/poet/tree/master/web

Makefile
- https://github.com/poetapp/poet/blob/master/makefile

Docker Files: 
- https://github.com/poetapp/poet/blob/master/Docker/web-poet-js-local.dockerfile
- https://github.com/poetapp/poet/blob/master/Docker/web-poet-js-remote.dockerfile

To preserve commit history, try to use [git filter-branch --prune-empty --subdirectory-filter web master](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/).

### LINKED ISSUE #2: Work Screen : Attributes : Author
The value for `author` can either be a plain string or the id of a profile in Poet.

When it's the ID of a profile, it should be displayed as a link to that profile, with the profile's name.

work author

### PR DESCRIPTION
**Pull request by wzalazar**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

## Description of Changes

Fix https://github.com/poetapp/explorer-web/issues/426

This PR introduces:

- Env vars for Netlify

### Warning

Merging to `master` automatically triggers a deploy in production.

### CODE REVIEW

**Comment by wzalazar** [comment]
@jwicks31 

When is necessary to read from?

https://github.com/poetapp/explorer-web/blob/9225834a9179246a3d03a8f5d130c5132f2ce2b4/webpack.config.js#L70-L76

I have a doubt here, Is possible to read deep keys? I mean `limit` and `visiblePageCount`

https://github.com/poetapp/explorer-web/blob/9225834a9179246a3d03a8f5d130c5132f2ce2b4/src/configuration.ts#L17-L26

**Comment by jwicks31** [comment]
@wzalazar these environment variables are set inside of the Netlify already. I don't think it's necessary to add them to the TOML file. We are missing the DATE_FORMAT variable there though. 

> @jwicks31
> 
> When is necessary to read from?
> 
https://github.com/poetapp/explorer-web/blob/9225834a9179246a3d03a8f5d130c5132f2ce2b4/webpack.config.js#L70-L76


I'm not sure how else to allow environment variables to be passed in individually?

**Comment by wzalazar** [comment]
@jwicks31 but the values are different for each environment. How you handle it on Netlify?

on the other hand, I didn't see these variables are set on Netlify

**Comment by wzalazar** [comment]
the issue was resolved ;)

**Pull request closed without merging**
