### PR TITLE
chore: update package-lock using npm 6.3.0

### PR DESCRIPTION
**Pull request by warrenv**
[PR Process](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-process) - [PR Review Checklist](https://github.com/poetapp/documentation/blob/master/process/pr-review.md#pr-review-checklist)

## Description of Changes

Fix 'npm ci' failure on travis because package.json and package-lock.json do not match.
Updated package-lock.json using npm 6.3.0.

Disabled the coverage reports. These are failing because 'npm ci' is not installing an
istanbul library from our nyc repo fork for some reason. Running 'npm install' installs 
it just fine. I have not been a able to find a way to configure travis ci to not run 'npm ci'.

### Warning

Merging to `master` automatically triggers a deploy in production.

### CODE REVIEW

**Comment by warrenv** [comment]
Travis is forcing the 'npm ci' command to run and it is not handling our fork of nyc correctly causing the coverage test to fail.

**Comment by wzalazar** [comment]
> Travis is forcing the 'npm ci' command to run and it is not handling our fork of nyc correctly causing the coverage test to fail.

can you create a new issue as a reference?

**Comment by warrenv** [comment]
Tracked here #239

**Comment by wzalazar** [comment]
excellent @warrenv !!!!

**Review by wzalazar — APPROVED** [review]
* [n/a] Tested changes manually
* [n/a] Checked accidental architectural/style changes
* [x] Reviewed entire diff
* [n/a] Unit tests
* [n/a] Documentation
* [x] Filenames and locations

**Review by geoffturk — APPROVED** [review]
* [n/a] Tested changes manually
* [n/a] Checked accidental architectural/style changes
* [x] Reviewed entire diff
* [n/a] Unit tests
* [n/a] Documentation
* [x] Filenames and locations

**Review by kennylavender — APPROVED** [review]
* [x] Reviewed entire diff

N/A
* [ ] Tested changes manually
* [ ] Checked accidental architectural/style changes
* [ ] Unit tests
* [ ] Documentation
* [ ] Filenames and locations

**Pull request merged**
