### PR TITLE
Adds package @po.et/stylelint-rules

### PR DESCRIPTION
**Pull request by wzalazar**
This PR introduces

- adds packages @po.et/stylelint-rules
- fixes styles

**Notes**: 
- Absolute path in Sass not working
- There are issues with the rule ```no-descending-specificity```, for this reason, I disabled the rule in specific places

### CODE REVIEW

**Comment by warrenv** [comment]
Can you run `rm -rf node_modules` and then `npm install` and see if package-lock.json is changed?
If so, please update it as part of this PR.

**Comment by wzalazar** [comment]
@warrenv I need to delete the ```package-lock.json``` also?

**Comment by warrenv** [comment]
No, it is not necessary to delete it.

**Comment by wzalazar** [comment]
ok, I removed ```node_modules``` and after that, I executed ```npm install``` but it didn't change ```package-lock.json```

**Comment by warrenv** [comment]
I wonder why mine is changing then? Ah, it's fsevents that is chaning -
probably because I am running on Linux and you are on a Mac.

**Comment by wzalazar** [comment]
yes, should be the S.O. I'm working on Mac.

**Review by warrenv — APPROVED** [review]

**Review by lautarodragan — APPROVED** [review]

**Pull request merged**
